LibraryManageSys/Controllers/ReaderController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using LibraryManageSys.Models;
using LibraryManageSys.DAL;
using LMS.Common;
using PagedList;

namespace LibraryManageSys.Controllers
{
    public class ReaderController : Controller
    {
        private LMSEntitys db = ContextFactory.GetCurrentContext();

        // GET: /Reader/
        public ActionResult Index(string keyword, int page = 1)
        {
            var viewData = db.readers.OrderByDescending(o=>o.createTime);
            if (!string.IsNullOrEmpty(keyword)) 
            {
                viewData.Where(o => o.readerName.Contains(keyword));
            }
            return View(viewData.ToPagedList(page,5) );
        }

        //get UserNamer from View
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Index(FormCollection Collection)
        {
            string readerName = Collection["readerName"];
            List<Reader> readers = new List<Reader>();
            IReaderDal iRedaerDal = RepositoryFactory.ReaderRepository;
            var _list = iRedaerDal.FindList(a => a.readerName.Contains(readerName), "readerName", true).ToList();
            return View(_list.ToPagedList(1,5));          
        }

        // GET: /Reader/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Reader reader = db.readers.Find(id);
            if (reader == null)
            {
                return HttpNotFound();
            }
            return View(reader);
        }

        // GET: /Reader/Create
        public ActionResult Create()
        {
            Reader reader = new Reader();
            try
            {
                if (Session["userName"] != null)
                {
                    reader.createName = Session["userName"].ToString();
                }
                else {
                    return RedirectToAction("Login","User");
                }    
            }
            catch (Exception e) {
                LogHelper.WriteLog(typeof(ReaderController),e);
                throw e;
            }
            return View(reader);
        }

        // POST: /Reader/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Reader reader)
        {
            reader.createTime = DateTime.Now;
            if (ModelState.IsValid)
            {
                try
                {
                    db.readers.Add(reader);
                    db.SaveChanges();
                }
                catch (Exception e) {
                    LogHelper.WriteLog(typeof(ReaderController), e);
                    throw e;
                }
                
                return RedirectToAction("Index");
            }

            return View(reader);
        }

        // GET: /Reader/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Reader reader = db.readers.Find(id);
            if (reader == null)
            {
                return HttpNotFound();
            }
            return View(reader);
        }

        // POST: /Reader/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include="readerId,readerName,phoneNum,Gender,email,balance,enableBorrowNum,createName,createTime")] Reader reader)
        {
            if (ModelState.IsValid)
            {
                db.Entry(reader).State = System.Data.Entity.EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(reader);
        }

        // GET: /Reader/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Reader reader = db.readers.Find(id);
            if (reader == null)
            {
                return HttpNotFound();
            }
            return View(reader);
        }

        // POST: /Reader/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Reader reader = db.readers.Find(id);
            db.readers.Remove(reader);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

LibraryManageSys/Views/Shared/DataBaseError.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Error</title>
</head>
<body>
    <hgroup>
        <h1>Error.</h1>
        <h2>An error occurred while processing your request!!</h2>
        <h2 class="text-center"> You can back to home page login again=>@Html.ActionLink("Login", "Login", "User")</h2>
    </hgroup>
</body>
</html>

LibraryManageSys/Views/Shared/MainContentLayout.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@Scripts.Render("~/bundles/main")
<!--左侧导航-->
<aside class="lyear-layout-sidebar">
    <!-- logo -->
    <div id="logo" class="sidebar-header">
        <a href="Book" class="site_title"><i class="mdi mdi-library"></i> <span>苏州大学</span></a>
    </div>
    <div class="lyear-layout-sidebar-scroll">
        <nav class="sidebar-main">
            <ul class="nav nav-drawer">
                <li class="nav-item"> <a href="Book"><i class="mdi mdi-home"></i> 首页</a> </li>
                <li class="nav-item nav-item-has-subnav">
                    <a href="javascript:void(0)"><i class="mdi mdi-book-multiple"></i> 图书管理</a>
                    <ul class="nav nav-subnav">
                        <li> @Html.ActionLink("图书查询", "Index", "Book") </li>
                    </ul>
                </li>
                <li class="nav-item nav-item-has-subnav">
                    <a href="javascript:void(0)"><i class="mdi mdi-account"></i> 读者管理</a>
                    <ul class="nav nav-subnav">
                        <li> @Html.ActionLink("读者管理", "Index", "Reader")</li>
                    </ul>
                </li>
                <li class="nav-item nav-item-has-subnav">
                    <a href="javascript:void(0)"><i class="mdi mdi-clipboard-check"></i> 借还书管理</a>
                    <ul class="nav nav-subnav">
                        <li>@Html.ActionLink("借书管理", "Index", "BorrowItem")</li>
                        <li>@Html.ActionLink("还书管理", "ReturnRecord", "BorrowItem")</li>
                    </ul>
                </li>
            </ul>
        </nav>
    </div>
</aside>
<!--End 左侧导航-->
<!--头部信息-->
<header class="lyear-layout-header">
    <nav class="navbar navbar-default">
        <div class="topbar">

            <div class="topbar-left">
                <div class="lyear-aside-toggler">
                    <span class="lyear-toggler-bar"></span>
                    <span class="lyear-toggler-bar"></span>
                    <span class="lyear-toggler-bar"></span>
                </div>
                <span class="navbar-page-title"> @ViewBag.Title </span>
            </div>

            <ul class="topbar-right">
                <li class="dropdown dropdown-profile">
                    <a href="javascript:void(0)" data-toggle="dropdown">
                        <img class="img-avatar img-avatar-48 m-r-10" src="~/images/admin.jpg" alt="@Session["userName"]" />
                        <span>@Session["userName"] <span class="caret"></span></span>
                    </a>
                    <ul class="dropdown-menu dropdown-menu-right">
                        @*<li> <a href="lyear_pages_profile.html"><i class="mdi mdi-account"></i> 个人信息</a> </li>*@
                        <li> @Html.ActionLink(" 修改密码", "EditPassword", "User", new { }, new { @class = "mdi mdi-lock-outline", data_toggle = "modal", data_target = "#gridSystemModal" })</li>
                        <li> <a href="javascript:void(0)"><i class="mdi mdi-delete"></i> 清空缓存</a></li>
                        <li class="divider"></li>
                        <li> @Html.ActionLink(" 退出登录", "Logout", "User", new { }, new { @class = "mdi mdi-logout-variant" }) </li>
                    </ul>
                </li>
                <!--切换主题配色-->
                <li class="dropdown dropdown-skin">
                    <span data-toggle="dropdown" class="icon-palette"><i class="mdi mdi-palette"></i></span>
                    <ul class="dropdown-menu dropdown-menu-right" data-stopPropagation="true">
                        <li class="drop-title"><p>主题</p></li>
                        <li class="drop-skin-li clearfix">
                            <span class="inverse">
                                <input type="radio" name="site_theme" value="default" id="site_theme_1" checked>
                                <label for="site_theme_1"></label>
                            </span>
                            <span>
                                <input type="radio" name="site_theme" value="dark" id="site_theme_2">
                                <label for="site_theme_2"></label>
                            </span>
                            <span>
                                <input type="radio" name="site_theme" value="translucent" id="site_theme_3">
                                <label for="site_theme_3"></label>
                            </span>
                        </li>
                        <li class="drop-title"><p>LOGO</p></li>
                        <li class="drop-skin-li clearfix">
                            <span class="inverse">
                                <input type="radio" name="logo_bg" value="default" id="logo_bg_1" checked>
                                <label for="logo_bg_1"></label>
                            </span>
                            <span>
                                <input type="radio" name="logo_bg" value="color_2" id="logo_bg_2">
                                <label for="logo_bg_2"></label>
                            </span>
                            <span>
                                <input type="radio" name="logo_bg" value="color_3" id="logo_bg_3">
                                <label for="logo_bg_3"></label>
                            </span>
                            <span>
                                <input type="radio" name="logo_bg" value="color_4" id="logo_bg_4">
                                <label for="logo_bg_4"></label>
                            </span>
                            <span>
                                <input type="radio" name="logo_bg" value="color_5" id="logo_bg_5">
                                <label for="logo_bg_5"></label>
                            </span>
                            <span>
                                <input type="radio" name="logo_bg" value="color_6" id="logo_bg_6">
                                <label for="logo_bg_6"></label>
                            </span>
                            <span>
                                <input type="radio" name="logo_bg" value="color_7" id="logo_bg_7">
                                <label for="logo_bg_7"></label>
                            </span>
                            <span>
                                <input type="radio" name="logo_bg" value="color_8" id="logo_bg_8">
                                <label for="logo_bg_8"></label>
                            </span>
                        </li>
                        <li class="drop-title"><p>头部</p></li>
                        <li class="drop-skin-li clearfix">
                            <span class="inverse">
                                <input type="radio" name="header_bg" value="default" id="header_bg_1" checked>
                                <label for="header_bg_1"></label>
                            </span>
                            <span>
                                <input type="radio" name="header_bg" value="color_2" id="header_bg_2">
                                <label for="header_bg_2"></label>
                            </span>
                            <span>
                                <input type="radio" name="header_bg" value="color_3" id="header_bg_3">
                                <label for="header_bg_3"></label>
                            </span>
                            <span>
                                <input type="radio" name="header_bg" value="color_4" id="header_bg_4">
                                <label for="header_bg_4"></label>
                            </span>
                            <span>
                                <input type="radio" name="header_bg" value="color_5" id="header_bg_5">
                                <label for="header_bg_5"></label>
                            </span>
                            <span>
                                <input type="radio" name="header_bg" value="color_6" id="header_bg_6">
                                <label for="header_bg_6"></label>
                            </span>
                            <span>
                                <input type="radio" name="header_bg" value="color_7" id="header_bg_7">
                                <label for="header_bg_7"></label>
                            </span>
                            <span>
                                <input type="radio" name="header_bg" value="color_8" id="header_bg_8">
                                <label for="header_bg_8"></label>
                            </span>
                        </li>
                        <li class="drop-title"><p>侧边栏</p></li>
                        <li class="drop-skin-li clearfix">
                            <span class="inverse">
                                <input type="radio" name="sidebar_bg" value="default" id="sidebar_bg_1" checked>
                                <label for="sidebar_bg_1"></label>
                            </span>
                            <span>
                                <input type="radio" name="sidebar_bg" value="color_2" id="sidebar_bg_2">
                                <label for="sidebar_bg_2"></label>
                            </span>
                            <span>
                                <input type="radio" name="sidebar_bg" value="color_3" id="sidebar_bg_3">
                                <label for="sidebar_bg_3"></label>
                            </span>
                            <span>
                                <input type="radio" name="sidebar_bg" value="color_4" id="sidebar_bg_4">
                                <label for="sidebar_bg_4"></label>
                            </span>
                            <span>
                                <input type="radio" name="sidebar_bg" value="color_5" id="sidebar_bg_5">
                                <label for="sidebar_bg_5"></label>
                            </span>
                            <span>
                                <input type="radio" name="sidebar_bg" value="color_6" id="sidebar_bg_6">
                                <label for="sidebar_bg_6"></label>
                            </span>
                            <span>
                                <input type="radio" name="sidebar_bg" value="color_7" id="sidebar_bg_7">
                                <label for="sidebar_bg_7"></label>
                            </span>
                            <span>
                                <input type="radio" name="sidebar_bg" value="color_8" id="sidebar_bg_8">
                                <label for="sidebar_bg_8"></label>
                            </span>
                        </li>
                    </ul>
                </li>
                <!--切换主题配色-->
            </ul>
        </div>
    </nav>
</header>
<!--End 头部信息-->

<div class="lyear-layout-content">
    <div class="container-fluid">
        @RenderBody()
    </div>
</div>

<style>
    .dropdown-menu > li > a > i {
        margin-right: 0px;
    }
</style>

LibraryManageSys/Views/Shared/ValidationSummary.cshtml
@model ModelStateDictionary

@if (!Model.IsValid)
{
    <div class="alert alert-success alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">×</span>
        </button>
        @foreach (var modelError in Model.SelectMany(keyValuePair => keyValuePair.Value.Errors))
        {
            <strong>@modelError.ErrorMessage</strong>
        }
    </div>
}


@*<div class="validation-summary-errors">
        <ul>
            @foreach (var modelError in
                     Model.SelectMany(keyValuePair => keyValuePair.Value.Errors))
            {
                <li>@modelError.ErrorMessage</li>
            }
        </ul>
    </div>*@

@*@Html.Partial("ValidationSummary", ViewData.ModelState);*@

LibraryManageSys/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - 图书管理系统</title>
    @Styles.Render("~/Content/css")
    @Styles.Render("~/Content/Defined.css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
</head>
<body>
    <div class="lyear-layout-web">
        <div class="lyear-layout-container">
            @*@Html.Partial("ValidationSummary", ViewData.ModelState);*@
            @RenderBody()
        </div>
        <footer class="footer-wrapper">
            <p>Copyright &copy; @DateTime.Now.Year - 图书管理系统</p>
        </footer>
    </div>
    @Html.Partial("EditorTemplates/Dialog", ViewData.ModelState);
    @RenderSection("scripts", required: false)
</body>
</html>